// Shared paths for the browser test harness.
//
// Everything is derived from this file's own location so the suite runs from
// any checkout — no absolute paths are baked in.
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'
import { existsSync, mkdirSync } from 'node:fs'

/** tools/browser-test */
export const HERE = dirname(fileURLToPath(import.meta.url))
/** repository root (two levels up) */
export const ROOT = resolve(HERE, '..', '..')
/** the plugin package under test */
export const PLUGIN = join(ROOT, 'dsh-live2d-pet')
/** screenshots and other evidence */
export const SHOTS = join(HERE, 'shots')
/** per-run Edge profiles (disposable, gitignored) */
export const PROFILES = join(HERE, '.profiles')
/** Screenshot / JSON output from the drivers. */
for (const dir of [PROFILES, SHOTS]) mkdirSync(dir, { recursive: true })
/** variant client bundles generated by make-variant.mjs */
export const VARIANTS = join(HERE, 'variants')

/** Candidate Edge/Chrome executables, first hit wins. */
const BROWSERS = [
  'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
  'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe',
  'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
  'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
  '/usr/bin/google-chrome',
  '/usr/bin/google-chrome-stable',
  '/usr/bin/chromium',
  '/usr/bin/chromium-browser',
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
]
export function browserPath() {
  for (const candidate of BROWSERS) {
    try { if (existsSync(candidate)) return candidate } catch { /* keep looking */ }
  }
  throw new Error('No Edge/Chrome found. Set one of: ' + BROWSERS.join(', '))
}

// The harness server each driver talks to. The suite gives every driver its
// own server (see run-suite.mjs) because the activity hub is process-global:
// two drivers nudging phases against one server stomp on each other, which is
// exactly what broke cdp-host-events and cdp-idle-return when the suite first
// went parallel.
export const BASE = process.env.PET_BASE ?? 'http://127.0.0.1:' + (process.env.PET_PORT ?? '8793')
